### ISSUE TITLE
Start app

### ISSUE THREAD

**Issue by sah4ez** [docdoku/docdoku-plm-docker#2]
I build server:
```
cd ~/docdoku-plm-server
mvn clean install 
```
Then:
```
cd ~/.docdoku-web-front/
npm install
bower install
grunt build
```
Then:
```
docker-compose up -d
```
And when I type URL: `localhost:13000`
I had an error:
```
Sorry

An unexpected error happened, please try again or contact support

   CODE[0] - 
```

**Comment by mguimard** [comment]
Hi, 

First thing: you don't need to build the web-front, only build if you need to deploy the built version (minified JS, etc...)

You need to access localhost:10080, not localhost:13000

You also need to make a small change to docdoku-web-front/app/webapp.properties (change 8080 with 10080)

I will document it better when I have time

**Comment by sah4ez** [comment]
Ok, when I changed `docdocky-web-front/app/webapp.properties.json` 8080 to 10080, I had an error:
```
Sorry

There's nothing here, the url link is incorrect
```

**Comment by mguimard** [comment]
Did you copy docdoku-plm-ear.ear to the `autodeploy` folder ?

**Comment by sah4ez** [comment]
Yes, I did copy.
But I fixed it, when I deployed EAR through GUI pyaray server
